### ISSUE TITLE
Export console in gui

### ISSUE THREAD

**Issue by TomBor** [mbloch/mapshaper#381] opened 2019-11-14 08:15 UTC
It would be useful sometimes to be able to export command passed in the console (in GUI mode).
For quick tasks or for people who don't use the command line and want to keep a log of what they have done inside mapshaper.

**Comment by mbloch** [comment] 2019-11-18 02:56
This is a dupe of issue #33. I just added an initial version of this feature. You can view the browser session as a command line string by running "history" in the browser console.

**Closed by mbloch** 2019-11-18 02:56 UTC
