### ISSUE TITLE
filter deleting wrong data

### ISSUE THREAD

**Issue by craigtone** [mbloch/mapshaper#552] opened 2022-08-16 21:47 UTC
I am using the online tool in console as follows:

filter 'FORESTNAME!=="Huron-Manistee National Forest"'

It ends up removing the data that is true instead of the data that is false?  I also tried invert and it did the same thing.

**Comment by mbloch** [comment] 2022-08-16 22:34
I was unable to replicate this. Can you send a sample dataset that causes the issue for you? Thanks!

**Comment by craigtone** [comment] 2022-08-17 13:50
The file I am using is 1Gb ... it is the US Forest Service Motor Vehicle Use Map (Roads).  Not sure how to share and it is difficult to download since the ArcGIS always errors out trying to download it.

**Comment by craigtone** [comment] 2022-08-17 14:35
Here is the ArcGIS link:[ ](https://data-usfs.hub.arcgis.com/datasets/usfs::motor-vehicle-use-map-roads-feature-layer/explore?location=40.202584%2C-113.359700%2C4.42)

**Comment by mbloch** [comment] 2022-08-17 16:05
I downloaded the link. The filter command seems to be working as expected, but the browser display is a bit confusing. Here's what I see after running your command with "invert" (zoomed in to Huron-Manistee):
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/1232222/185186756-1103b9f4-d2b9-42e3-9992-ae037adcd9de.png">

Note that the removed shapes are still visible as ghosted blue lines, and line intersections are still displayed for the removed shapes. I'm thinking that the removed shapes should probably be removed completely, rather than being retained internally and displayed as ghosted lines.

Also note that the following two commands are equivalent:
`filter 'FORESTNAME !== "Huron-Manistee National Forest"' invert`
`filter 'FORESTNAME == "Huron-Manistee National Forest"'`

**Comment by craigtone** [comment] 2022-08-17 16:27
I had the invert before the expression ... maybe that was the problem?  When I was running it, it kept saying retained 176,478 features.  Thanks!

**Comment by mbloch** [comment] 2022-09-02 14:08
I wasn't able to reproduce the problem, so i'm going to close this...

**Closed by mbloch** 2022-09-02 14:08 UTC
