### ISSUE TITLE
Error in skiping shape when shape.isNull == true

### ISSUE THREAD

**Issue by JackShell2020** [mbloch/mapshaper#494] opened 2021-07-22 09:26 UTC
node v12.18.1
mapshaper v 0.6.6

### problem
I have a shapefile width 27 features,  need to get geojson by using command `-i input.shp -o export.json` .
however, i got an bad result, the geometries is an empty array

then i worked it with a package named `shapefile` , get a result with  54 features,
like this: `[ null, feature, null, feature, ... ]`

one empty, one feature, one empty, one feature ...

so there must be some problem with the shapefile.
but mapshaper should compatible it

### solution
then, i debug the code in mapshaper

find out the reason and the solution.
there are something wrong in function `readNextShape` , 
you got a bad work in  `shape.id < expectedId`, then passed the real feature.

when the shape feature is null, it doesn't have id, 
and when the shape feature is not null, it's id is always < expectedId

one way to resolve `expectedId` 
the other way , ignore the condition `shape.id < expectedId` and return the shape feature, because doing fuc  `reader.forEachShape`, you had skipped the feature(null)

![image](https://user-images.githubusercontent.com/39986367/126616392-46d357b8-e6a4-4a61-844e-081bdc5286ee.png)

**Comment by JackShell2020** [comment] 2021-07-22 09:27
the first way to solution
![image](https://user-images.githubusercontent.com/39986367/126617555-d178db45-c542-42c8-b0d4-1852c90cda18.png)

**Comment by mbloch** [comment] 2021-07-22 11:15
Hi!
Can you send me your Shapefile, so I can reproduce the issue and possibly find a more targeted solution? Your proposed fix might allow this Shapefile to be read, but it looks to me like it would cause problems for some other Shapefiles that follow the Shapefile specification.

**Comment by mbloch** [comment] 2021-08-01 05:43
I'm closing this because I don't have a sample Shapefile to test with.

**Closed by mbloch** 2021-08-01 05:43 UTC

**Comment by mbloch** [comment] 2021-08-03 23:39
It looks like the problem is related to the character encoding of the .dbf file. Mapshaper will not import a Shapefile if the encoding is unknown... and the program is unable to automatically detect this particular encoding (it looks like GB 2312 (国标). You can import the file like this:
```
mapshaper encoding=gb2312 1303042021s2.shp
```

If you're using the website, you can give the encoding here:
![image](https://user-images.githubusercontent.com/1232222/128099607-ed23ab2f-c31a-4e38-8cd3-039c62f34986.png)

**Comment by JackShell2020** [comment] 2021-08-04 01:29
no

it can be  worked out  when importing  `.shp  .shx`  without set encoding

in my business， i will just got a file `xxx.shp` .  no dbf,  no shx

in this case, although i set encoding,  it still dosen't work 

you can fully close this issue. I have solved by the first way,

and  doesn't cause any problems with testing almost twenty Shapefiles producted from 7 companies,

by website\ by command

**Comment by mbloch** [comment] 2021-08-04 03:31
I see, you want to import the .shp file without the .shx (shape index) file. Now I can reproduce the issue that you were having.

Without a .shx file, mapshaper is only able to read Shapefiles reliably that contain records with sequential ids.

Your sample .shp file has an unusual format. It contains pairs of records with the same id: a null record, followed by a record with valid geometry. Mapshaper imports the null record and skips past the record with geometry.

Your solution skips null records. This works well for the Shapefiles that you have, but will cause problems for other Shapefiles that contain valid null records. For this reason, i don't want to merge your fix.

You are correct to point out that mapshaper's null records are missing record ids. This looks like a bug to me, and I'll fix it. 

Thanks for getting in touch!
--mbloch
