### ISSUE TITLE
Incorrect polygon erasure

### ISSUE THREAD

**Issue by Xyrus-WS** [mbloch/mapshaper#337] opened 2019-05-03 20:26 UTC
Hello,

First, excellent application. 👍 

Now onto the issue. It appears the clipping/erase functionality has some issues. Attached are two files. The 20140101.zip file contains a shapefile full of sample data. The other file contains the Natural Earth 10m lakes shapefile. Both the files contain valid geometries.

If you attempt to erase the lakes from the sample file, you'll get a result where some of the lakes are erased, some lakes are drawn but not erased, and some are not erased at all.

Mapshaper doesn't appear to indicate that there are any errors, even with verbose enabled, and unfortunately I haven't been able to come up with a simpler case that exhibits this behavior.

The command is just a basic erase command:
mapshaper test.shp -erase ne_10m_lakes.shp -o out.shp

[20140101.zip](https://github.com/mbloch/mapshaper/files/3143455/20140101.zip)
[10m_physical.zip](https://github.com/mbloch/mapshaper/files/3143457/10m_physical.zip)

**Comment by nvkelso** [comment] 2019-05-03 21:14
I use MapShaper in the build process for Natural Earth. Does the https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries_lakes.zip file exhibit this type of problem, too?

**Comment by Xyrus-WS** [comment] 2019-05-03 21:38
As far as I can tell, the issue isn't with the NE geometry. It's the combination of the NE geometry with geometry similar in nature to the sample I posted.

For example, when I performed the same operation but used the NE 10m land shapefile instead of the sample data, it appeared to work correctly, though admittedly I didn't examine every nook and cranny of the result.

I've tried creating a simpler case to reproduce the effect, but so far haven't been successful in doing so.

If I run the operation using QGIS, ogr2ogr, or my own thrown together clipper the results appear correct. However, mapshaper is faster. :)

**Comment by mbloch** [comment] 2019-05-04 15:32
Thanks for reporting this :)
Interesting sample file... I was able to reproduce the issue... I'll try to fix the problem soon.

**Comment by mbloch** [comment] 2019-05-05 10:05
I released a new version that should fix this problem. There was a bug that affected erasing and clipping when an erase/clip polygon rings was completely contained inside a hole in one of the target polygons. I'm surprised the bug went unnoticed for so long!

**Comment by mbloch** [comment] 2019-05-05 17:51
@nvkelso I checked ne_10m_admin_0_countries_lakes, since you asked about it. There is only one place that was affected by this bug.

<img width="265" alt="Screen Shot 2019-05-05 at 1 44 10 PM" src="https://user-images.githubusercontent.com/1232222/57198011-ff63e080-6f3b-11e9-990d-c7d2f591241d.png">

Do you see the little island in Lake Malawi, that is showing as part of Mozambique in the screenshot above? That island belongs to Malawi, not Mozambique, but before this bug fix, mapshaper assigned it to both Malawi and Mozambique. This is the only location in countries_lakes that was affected by issue 337.

**Comment by nvkelso** [comment] 2019-05-05 19:24
Thank you, sir!

**Comment by mbloch** [comment] 2019-05-06 15:04
I'm closing this as fixed... @Xyrus-WS, feel free to re-open if you see any more erase-related problems.

**Closed by mbloch** 2019-05-06 15:04 UTC
