### ISSUE TITLE
Preview misses most items

### ISSUE THREAD

**Issue by Dekkerb** [mbloch/mapshaper#572] opened 2023-01-17 09:55 UTC
![image](https://user-images.githubusercontent.com/7647357/212866366-ccd46cf2-1874-4ed7-8605-f02cb07f876d.png)
This is a map of over 30 F1-circuits, all styled the same (red lines). But only a few are actually shown - see attached screenshot. The view changes (randomly?) when I zoom in, showing a different set but never all circuits.

**Comment by Dekkerb** [comment] 2023-01-17 09:58
[F1circuits.zip](https://github.com/mbloch/mapshaper/files/10433691/F1circuits.zip)

**Comment by mbloch** [comment] 2023-01-17 19:15
Thanks for reporting this, and for providing a sample dataset!. The flickering was caused by a rendering optimization that skipped drawing of shapes with coordinates that all round to the same pixel location. I just released a new version with a fix for this problem. It should solve the problem.

**Closed** 2023-01-17 22:06 UTC
