### ISSUE TITLE
Renaming a field changes the field's type

### ISSUE THREAD

**Issue by colindm** [mbloch/mapshaper#584] opened 2023-04-27 02:11 UTC
command 1:
`
-i ${precinctsOutput} name=precincts
 -rename-fields DPop20=POP20
-o ${censusBlocksOutput} format=geojson
`
command 2:
`
-i ${censusBlocksOutput}
-dissolve CNTYVTD sum-fields=DPop20
-o ${precinctsOutput} format=geojson
`

The above code outputs a geoJSON with the field DPop20 that is summed like a string (i.e "2"+"2"="22" rather than 2+2=4). If I get rid of the line ` -rename-fields DPop20=POP20` it sums the values together normally. Replacing it with `-each 'POP20 = DPop20' target=censusBlocks ` doesn't work either.

**Comment by colindm** [comment] 2023-04-27 02:37
Found a workaround that worked: `-each 'DPop20 = Number(POP20)' target=censusBlocks`

**Comment by mbloch** [comment] 2023-04-27 15:47
@colindm Can you provide an example file to help me reproduce this issue? I want to confirm that `POP20` contains only numerical values.

**Comment by mbloch** [comment] 2023-05-02 13:23
unable to reproduce -- closing

**Closed by mbloch** 2023-05-02 13:23 UTC
