### ISSUE TITLE
shp file export on website broken?

### ISSUE THREAD

**Issue by acdoering** [mbloch/mapshaper#182] opened 2017-04-24 09:59 UTC
Hi, 
when I'm exporting the shape file from the mapsite, it's a zip file, but it doesn't open - winzip complains about central directory missing, or some such (error message german). Any help appreciated...
Thx and regards
Andreas

**Comment by mbloch** [comment] 2017-04-24 13:56
Shapefile export is working fine for me. Do you have some time to troubleshoot the problem?

First of all, is the downloaded .zip file about the size that you'd expect? If it's less than 1K, it might be an error message pretending to be a .zip file... you could open it in a text editor and see if there's a useful message there. 

If the file is about the right size, is there anything about the name of the file or the data layer(s) inside that might cause buggy behavior in mapshaper, like non-ascii characters? If so, could you try exporting a dataset with a different name to see if that might be the issue?

I haven't run into this problem before, so these are just wild guesses. Please let me know if you are able to narrow this down.

If you send me your data files, I can see if there's something about these particular files that is causing the problem.

Thanks
mbloch

**Comment by acdoering** [comment] 2017-04-24 20:28
being german zip code shapefiles, they do have non-ascii placenames in the notes... it's this file: https://www.suche-postleitzahl.org/download_files/public/plz-gebiete.shp.zip
size of zip downloaded seems okay to me (5mb instead 39mb after heavy simplification)
all foreign shapefiles I just tried to download can't be import (size of header doesn't match), so I'm giving up on finding a 100%-plain-ascii shapefile for now...

**Comment by acdoering** [comment] 2017-04-24 21:00
obviously, it's not about your program, maybe about IE11 or my company's setup. I used another computer to run the process again (firefox on mac), and the resulting zip is fine. file is actually even smaller (2 mb at 1%), and opens fine even on original computer (IE11 on win) in winzip when zip is transferred back to original computer... 
I attach the broken file, in case this helps.
[plz-gebiete.zip](https://github.com/mbloch/mapshaper/files/953127/plz-gebiete.zip)
With the simplification I'm all set - thanks a lot for your support... and the tool!!

**Comment by mbloch** [comment] 2017-04-25 14:57
Thanks for reporting this problem -- I don't often test on Windows, so I rely on user feedback to catch Windows-only bugs.

I reproduced this problem on IE11... it doesn't seem to occur on Edge. I'll try to get this fixed soon.

**Comment by mbloch** [comment] 2017-04-26 04:32
I pushed a fix and updated mapshaper.org.

The problem was in the zip.js module (https://github.com/gildas-lormeau/zip.js). Fortunately there was a simple way to fix the error.

**Closed by mbloch** 2017-04-26 04:32 UTC

**Comment by mbloch** [comment] 2017-04-28 18:30
I filed an issue in the zip.js repo to report this bug:
https://github.com/gildas-lormeau/zip.js/issues/171
